app3-deployment.yaml

deployment.yaml


apiVersion: apps/v1
kind: Deployment
metadata:
  name: food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food
  template:
    metadata:
      labels:
        app: food
    spec:
      containers:
      - name: c1
        image: durgasaib/food
        ports:
        - containerPort: 80
