#Namespace

apiVersion: v1
kind: Namespace
metadata:
  name: qa

-----

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecomm
  template:
    metadata:
      labels:
        app: ecomm
    spec:
      containers:
      - name: c1
        image: durgasaib/ecomm
        ports:
        - containerPort: 80
----------
apiVersion: v1
kind: Service
metadata:
  name: ecomm-svc
  namespace:qa
spec:
  type: NodePort
  selector:
    app: ecomm
  ports:
    app: ecomm
  ports:
    - ports:80
      targetPort:80
      nodeport: 30008






